export const resortDetails = {
  entoto: {
    name: "kuriftu resort & spa Entoto",
    region: "ENTOTO PARK, ADDIS ABABA",
    address: "321 Lake View Avenue, Bishoftu, Ethiopia",
    description:
      "Kuriftu Entoto Adventure Park offers an off the beaten path experience in the heart of the Entoto Mountain. With an abundance of eucalyptus trees, this dense forest is considered to be the lungs of Addis Ababa with significant cultural and historical relevance. Telling the story of the founding of Addis Ababa from the time of Emperor Menelik II. The Adventure Park captures the beauty of this sacred location by highlighting nature based adventure tourism activites that allow families and tourists alike to emmerse themselves within this ecosystem. From activities ranging from rock-climbing to horse back riding and seculded glamping accommodations, this destination is truly one of a kind!",
    phone: "+251905061020",
    latitude: 9.0846279,
    longitude: 38.7383589,
    location: "14.9 km from Addis Ababa Bole International Airport",
    email: "booking@kurifturesorts.com",
    rating: 5,
    cover_image: "https://example.com/images/kuriftu-bishoftu.jpg",
    cover_video:
      "https://player.vimeo.com/video/705340877?api=1&autoplay=1&controls=0&sidedock=0&loop=1&title=0&byline=0&portrait=0&muted=1&background=1",
  },
  bishoftu: {
    name: "Kuriftu Resort & Spa Bishoftu",
    region: "LAKE KURIFTU, BISHOFTU",
    address: "",
    description: "Located on the northen tip of Bishoftu encompassing the smallest of the four lakes lies our flagship resort, Kuriftu Resort & Spa Bishoftu. Born from Mr. Tadiwos's vision to create luxury resort destinations in neighboring cities of the capital, this resort made its mark in 2007 as the first 5-star resort in the country. Kuriftu has redefined the meaning of service in Ethiopia, with an outstanding track record and dedicated loyalty program that keeps our guests more than satisfied, Kuriftu Bishoftu is a home away from home",
    phone: "+251924949494",
    latitude: 8.779961,
    longitude: 39.003129,
    location: "53.7 km from Addis Ababa Bole International Airport Lake Bishoftu Ethiopia",
    email: "booking@kurifturesorts.com",
    rating: 5,
    cover_image: "",
    cover_video: "https://i.vimeocdn.com/video/1424163963-f27181110b0a660d338609445dfe490fa8e89d7462ab4ef421657b96b4b12278-d?mw=80&q=85",
  },
  laketana: {
    name: "Kuriftu Resort & Spa Lake Tana",
    region: "LAKE TANA, BAHIRDAR",
    address: "",
    description: "Located in the capital of the Amhara Region, Bahirdar, Kuriftu Resort & Spa Lake Tana represents the Kuriftu brands second resort venture. As we seek to expand across Ethiopia, Lake Tana with its historic and cultural value was the perfect choice for expansion. Paired with scenic views, wildlife excursions and religious routes - this destination offers a new adventure for our Kuriftu family!",
    phone: "+251920959797",
    latitude: 11.598445,
    longitude: 37.383701,
    location: "491 km from Addis Ababa Bole International AirportLake Tana Ethiopia",
    email: "booking@kurifturesorts.com",
    rating: 5,
    cover_image: "",
    cover_video: "https://i.vimeocdn.com/video/1428926192-767c7d513d1832ddc2d878812fdde13a8626ed76192b93efcfa7fe0145fa7059-d?mw=80&q=85",
  },
  awash: {
    name: "Kuriftu Resort & Spa Awash Falls",
    region: "AWASH NATIONAL PARK",
    address: "",
    description: "Located on the Southern tip of Awash National Park, our one-of-a-kind boutique resort suspended over a waterfall places guests at an elevation that is unique to our property. With views of crocodiles on the river bank, the refreshing mist from the edge of the falls paired with unmatched scenery, we offer the ultimate experience to our visitors",
    phone: "+251944448800",
    latitude: 8.779961,
    longitude: 39.003129,
    location: "211 km from Addis Ababa Bole International Airport Awash Park Ethiopia",
    email: "booking@kurifturesorts.com",
    rating: 5,
    cover_image: "",
    cover_video: "https://i.vimeocdn.com/video/1454464818-8fc0d521310cd49a168c1714ccde2133d8b1dfc61dacbf3d4c87fe7c9f937003-d?mw=80&q=85",
  },
};
